# Generated by Django 5.2.5 on 2025-11-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(max_length=50),
        ),
    ]
